<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240921094123 extends AbstractMigration
{
    #[\Override]
    public function getDescription(): string
    {
        return 'Create PERMISSION table';
    }

    #[\Override]
    public function up(Schema $schema): void
    {
        $this->addSql(
            'create table permission (
                  id INT generated by default as IDENTITY not null,
                  name VARCHAR(255) not null,
                  description TEXT DEFAULT NULL,
                  primary key(id)
            )',
        );

        $this->addSql('create unique index UNIQ_IDENTIFIER_NAME on permission (name)');

        $this->addSql(
            'create table user_permission (
                  user_id INT not null,
                  permission_id INT not null,
                  primary key(user_id, permission_id)
             )',
        );

        $this->addSql('create index IDX_472E5446A76ED395 on user_permission (user_id)');
        $this->addSql('create index IDX_472E5446FED90CCA on user_permission (permission_id)');

        $this->addSql(
            'alter table user_permission
                add constraint FK_472E5446A76ED395 foreign key (user_id) references "user" (id) on delete cascade not DEFERRABLE INITIALLY IMMEDIATE',
        );
        $this->addSql(
            'alter table user_permission
                  add constraint FK_472E5446FED90CCA foreign key (permission_id) references permission (id) on delete cascade not DEFERRABLE INITIALLY IMMEDIATE',
        );
    }

    #[\Override]
    public function down(Schema $schema): void
    {
        $this->addSql('CREATE schema public');
        $this->addSql('alter table user_permission drop constraint FK_472E5446A76ED395');
        $this->addSql('alter table user_permission drop constraint FK_472E5446FED90CCA');
        $this->addSql('drop table permission');
        $this->addSql('drop table user_permission');
    }
}
