<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240921192649 extends AbstractMigration
{
    #[\Override]
    public function getDescription(): string
    {
        return 'Create EMAIL table';
    }

    #[\Override]
    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(
            'create table email (
              id INT generated by default as identity not null, 
              from_email VARCHAR(255) not null, 
              from_name VARCHAR(255) default null, 
              to_email VARCHAR(255) not null, 
              subject VARCHAR(255) not null, 
              body TEXT not null,
              cc JSON default null,
              bcc JSON default null,
              reply_to VARCHAR(255) default null,
              primary key(id)
            )',
        );
    }

    #[\Override]
    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE schema public');
        $this->addSql('drop table email');
    }
}
