<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240921092003 extends AbstractMigration
{
    #[\Override]
    public function getDescription(): string
    {
        return 'Creates USER table';
    }

    #[\Override]
    public function up(Schema $schema): void
    {
        $this->addSql(
            'create table "user" (
                id INT generated by default as identity not null,
                email VARCHAR(180) not null,
                password VARCHAR(255) not null,
                firstname VARCHAR(255) not null,
                lastname VARCHAR(255) not null,
                middlename VARCHAR(255) default null,
                image VARCHAR(255) default null,
                bucket VARCHAR(255) default null,
                contact_information JSON default null,
                image_original_filename VARCHAR(255) default null,
                is_active BOOLEAN not null,
                login_attempts INT not null,
                is_disabled BOOLEAN not null,
                slug VARCHAR(255) not null,
                primary key(id)
            )',
        );

        $this->addSql('create unique index UNIQ_IDENTIFIER_EMAIL on "user" (email)');
    }

    #[\Override]
    public function down(Schema $schema): void
    {
        $this->addSql('create schema public');
        $this->addSql('drop table "user"');
    }
}
