<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240921152456 extends AbstractMigration
{
    #[\Override]
    public function getDescription(): string
    {
        return 'Create RESET_PASSWORD_REQUEST table';
    }

    #[\Override]
    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(
            'create table reset_password_request (
                id INT generated by default as IDENTITY not null,
                selector VARCHAR(20) not null,
                hashed_token VARCHAR(100) not null,
                requested_at TIMESTAMP(0) without time ZONE not null,
                expires_at TIMESTAMP(0) without time ZONE not null,
                _user_id INT not null,
                primary key(id)
            )',
        );
        $this->addSql('create index IDX_7CE748AD32632E8 on reset_password_request (_user_id)');
        $this->addSql(
            'alter table reset_password_request
                  add constraint FK_7CE748AD32632E8 foreign key (_user_id) references "user" (id) not DEFERRABLE INITIALLY IMMEDIATE',
        );
    }

    #[\Override]
    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE schema public');
        $this->addSql('alter table reset_password_request drop constraint FK_7CE748AD32632E8');
        $this->addSql('drop table reset_password_request');
    }
}
