# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            string $signingKey: '%env(APP_SECRET)%'
#            string $environment: "%kernel.environment%"
            string $projectDir: "%kernel.project_dir%"
            string $publicDir: "%kernel.project_dir%/public"

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Utils/'
            - '../src/Services/'
            - '../src/Form/'
            - '../src/Kernel.php'

    App\Service\UserService:
        class: App\Service\UserService
        autowire: true

    App\Service\EmailService:
        class: App\Service\EmailService
        autowire: true

    App\Service\ResetPassword\ResetPasswordHelper:
        class: App\Service\ResetPassword\ResetPasswordHelper
        autowire: true
        arguments:
            $resetRequestLifetime: 7200
            $requestThrottleTime: 60

    App\Service\ResetPassword\ResetPasswordService:
        class: App\Service\ResetPassword\ResetPasswordService
        autowire: true

    App\Service\ResetPassword\ResetPasswordTokenGenerator:
        class: App\Service\ResetPassword\ResetPasswordTokenGenerator
        autowire: true
